name            = Common Config Plugin
description     = A common config plugin for store config
version         = 1.0.0

url             = https://github.com/Akazukin-Team/Java-Common-Plugin-Config

vendor          = Akazukin Team
vendor-url      = https://github.com/Akazukin-Team

groupId         = org.akazukin
artifactId      = common-config

archiveBaseName = CommonConfig
